services:
  mongo: 
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shivansh
      - MONGO_INITDB_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend.dev
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_CONN=mongodb://shivansh:secret@mongo:27017
      - MY_PLATEFORM_PREFIX=shivansh
      - PORT=3000
      - JWT_SECRET_KEY=secret
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongo
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
      - VITE_FRONTEND_URL=http://localhost:5173
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
  
    