FROM   node:24-alpine  AS builder

WORKDIR /app/backend

COPY  ./backend/package*.json   ./
RUN npm install

COPY  ./backend   ./

RUN npm run build

FROM  node:24-alpine

WORKDIR   /app/backend
COPY    ./backend/package*.json   ./

RUN   npm install --omit=dev

COPY   --from=builder   /app/backend/dist    ./dist

EXPOSE 3000

CMD [ "npm", "run", "start" ]