FROM   node:24-alpine  AS builder

WORKDIR /app/backend

COPY ./backend/package.json       ./
COPY ./backend/package-lock.json  ./
COPY ./backend/tsconfig.json   ./

RUN npm install

COPY ./backend/src    ./src

RUN npm run build

FROM  node:24-alpine AS runner

WORKDIR /app/backend

COPY  backend/package.json       ./
COPY  backend/package-lock.json  ./

RUN npm install

COPY --from=builder  /app/backend/dist  ./dist

EXPOSE 3000

CMD [ "npm", "start" ]



