name: Build Docker Image and deploy to EC2 instance

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - "docker/Dockerfile.frontend.prod"
      - ".github/workflows/cd_frontend_prod.yml"

jobs:
  build_frontend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/Dockerfile.frontend.prod
          build-args: |
            VITE_BACKEND_URL=${{secrets.VITE_BACKEND_URL}}
            VITE_FRONTEND_URL=${{secrets.VITE_FRONTEND_URL}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/secondbrain_frontend:${{github.sha}}

  deploy_frontend:
    needs: build_frontend_image
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the machine and Start the Frontend Container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p ~/second_brain
            cd ~/second_brain

            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/secondbrain_frontend:${{github.sha}}

            sudo docker rm -f secondbrain_frontend || true

            sudo docker run -d -p 5173:80 --name secondbrain_frontend ${{secrets.DOCKERHUB_USERNAME}}/secondbrain_frontend:${{github.sha}}

            sudo docker image prune -f
